apiVersion: v1
kind: Pod
metadata:
  name: gpu-operator-test
  namespace: jellyfin
spec:
  runtimeClassName: nvidia
  restartPolicy: OnFailure
  containers:
    - name: cuda-vector-add
      image: nvidia/cuda:12.3.2-base-ubuntu22.04
      command: ["/bin/bash"]
      resources:
        limits:
          nvidia.com/gpu: 3